### ISSUE TITLE
Retry .NET 6

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.Headless#1067]

**Comment by moreal** [comment]
I researched to bump to .NET 6 and the headless application's memory usage often reached over 20GB.

I got a memory snapshot from a custom Docker image containing the dotMemory CLI tool based on the v100110 image.

![image](https://user-images.githubusercontent.com/26626194/155914004-145464ae-0cb9-47b5-8e37-ab8deb1f6812.png)
![image](https://user-images.githubusercontent.com/26626194/155914424-10ff41a1-1ec6-4027-b675-ba6ec10b5504.png)

I could see managed memory uses about 7~8 GB but unmanaged memory uses 14~15 GB.
Once, we mistrust about `LRUCache`'s implementation, it used 3.7 GB from `BlockSet`.

**Comment by moreal** [comment]
Additionally, there was also an issue about `RankingBattle.Result`. `RankingBattle` action was mutable and stored its battle result. They were about 6GB.

![image](https://user-images.githubusercontent.com/26626194/159235782-e59d939c-a6a2-4f13-b875-cf978540651a.png)

**Comment by moreal** [comment]
Though I applied a new image to decrease LRU cache size into 2 based on .NET 6, it met OOM on Kuberntes environment. But. according to CloudWatch histories, it was used only 40% memory. We couldn't understand that situation and started to mistrust that base image. 🤔 We should search about OOM killer difference between Debian 10 and Debian 11.

**Comment by moreal** [comment]
On March 22, I applied v100140 + .NET 6 image to the cluster and it might be replaced on March 29. It seems there is no problem 🤔 I'll re-apply v100160 + .NET 6 image.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/26626194/161519595-41a8be7b-a144-4b32-830c-5300fdc5bc4d.png">
