### ISSUE TITLE
Re-namining project

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.Headless#116]
I guess "NineChonicles.Standalone" isn't proper to describe its behavior because it hasn't any UI and needs Unity Player as the frontend.

so I suggest "NineChronicles.Headless" for a new name for this project and target assembly name.

**Comment by moreal** [comment]
I copied the checklist from https://github.com/planetarium/NineChronicles.Standalone/pull/207#issuecomment-740467890. This should be updated with the link of the pull request updated.

- [ ] Update the code referring the name in the repository.
- [ ] Update the docs in the repository.
- [ ] Rename the repository.
- [ ] Update other projects referring this project.
- [ ] Update the external docs:
    - [ ] Update [the articles](https://forum.nine-chronicles.com/search?q=standalone) on the 9C forum.
- [ ] Update the internal deployment settings.
