### ISSUE TITLE
`Push Docker image` manifest error in `GitHub workflow`

### ISSUE THREAD

**Issue by area363** [planetarium/NineChronicles.Headless#1182]
Error reference: https://github.com/planetarium/NineChronicles.Headless/runs/5973111483?check_suite_focus=true

**Comment by moreal** [comment]
This issue's error cannot be found.

<img width="1062" alt="image" src="https://github.com/planetarium/NineChronicles.Headless/assets/26626194/d0a53efa-ced3-446d-b43d-5b692852af00">
