### ISSUE TITLE
Insert `LastCommit` when mining a new block.

### ISSUE THREAD

**Issue by limebell** [planetarium/NineChronicles.Headless#1298]
`BlockCommit` is a list of vote for the previous block, is required for current block's block header.

Todo:
- [x] Add a getter for `VoteSet` for previous blocks.
- [x] Inject `VoteSet` for previous block when mining.

**Comment by moreal** [comment]
It seems resolved 🤔 , If there is a remained job, please reopen this issue @limebell  🙏🏻
