### ISSUE TITLE
Certain subscriptions may overload clients

### ISSUE THREAD

**Issue by BasixKOR** [planetarium/NineChronicles.Headless#1315]
## Description
After switching from `nodeStatus.tip.index` to `tipChanged` subscription, 9c-launcher has experienced severe performance issues due to too frequent subscription responses.

Although this is not a bug per se, it may help if we could introduce a way to limit the frequency of the response of these subscriptions such as throttling etc.

## Reproduction
Using Apollo Client with React, assuming the basic configuration is completed, this snippet will cause the application to be stuck for a while.

```typescript
import { useSubscription, gql } from "@apollo/client";

const TIP_SUBSCRIPTION = gql`
subscription Tip {
  tipChanged {
    index
  }
}
`;

function Component() {
  useSubscription(TIP_SUBSCRIPTION);
  return null;
}
```

### Executed environment

- [ ] Docker (tag: )
- [ ] Through `dotnet run` (commit: ...(e.g. ))
- [x] Through NineChronicles launcher (version: ... (e.g. v1000080)): around v100200

### Executed GraphQL query

```graphql
subscription Tip {
  tipChanged {
    index
  }
}
```

## Expected behaviour
We could let the client limit the frequency by passing some arguments.

## **Additional context**
This subscription has been introduced for easing the load of an RPC server.

**Comment by BasixKOR** [comment]
Update on the issue: the launcher currently circumvents this issue via handling the updates manually and schedule them. See https://github.com/planetarium/9c-launcher/pull/1536 for details.

**Comment by moreal** [comment]
I'm so sorry because it has taken too long time. I fixed it in https://github.com/planetarium/NineChronicles.Headless/pull/2245 PR.
