### ISSUE TITLE
Drop `LiteDB` support and `--store-type` option

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.Headless#1438]
I think that we aren't using `LiteDB` implementation for 9c seriously.

**Comment by BasixKOR** [comment]
As we're exploring ways to use LiteDB or other in-memory stores as a development environment, I'd love to see another in-memory store to replace LiteDB.

**Comment by moreal** [comment]
In libplanet, there is an in-memory store called [`MemoryStore`][memory-store]. It seems better to suggest a `memory` store type in this issue, or to open a new issue like that.

[memory-store]: https://docs.libplanet.io/0.39.0/api/Libplanet.Store.MemoryStore.html

**Comment by U-lis** [comment]
### Working Plan
1. For backward compatibility, leave `Default` option as-is.
2. Add `Memory` option to use `MemoryStore`.
3. Make it work and Test
