### ISSUE TITLE
Import snapshot feature from NineChornicles.Snapshot

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.Headless#1456]
When the `NineChronicles.Headless` doesn't exist, the `NineChronicles.Snapshot` was introduced early. And the `NineChronicles.Headless` was also introduced. They were in the one repository called `nekoyume-unity` but they are separated now.

In my thought, the `NineChronicles.Snapshot` and the `NineChronicles.Headless` can be merged and provided as one command like geth in Ethereum. I think it is enough to have only one tool to handle operations for NineChronicles.

The resulting form should be discussed but in my short thought, it'll be like `NineChronicles.Headless.Executable snapshot ...`.

Written by @moreal.

**Comment by area363** [comment]
https://github.com/planetarium/NineChronicles.Headless/pull/1799 submitted for review.

**Comment by area363** [comment]
Resolved by https://github.com/planetarium/NineChronicles.Headless/pull/1799.
