### ISSUE TITLE
Survey current implementation (i.e., `GenesisCommand`)

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.Headless#1461]

**Comment by U-lis** [comment]
참고 : https://www.notion.so/planetarium/2022-08-05-DX-daily-0db349dbcaec4b11aaee5052cdb1cc6e

**Comment by U-lis** [comment]
- 참고용 문서 : [Notion](https://www.notion.so/planetarium/30df8ceb6a9345bb85f8ae564a5b9b1a#8f84c4d09605453899dcf285a32903d6)
- GenesisCommand 조사 및 계획 : [Notion](https://www.notion.so/planetarium/Rebuild-genesis-012393c7f47c4b8fb16fd5fcef8febdc)

**Comment by U-lis** [comment]
neon-genesis ~evangelion~ command 를 만들고 있습니다.
`tablePath` 이외의 값은 사실 practical 하게는 필수가 아닌데 Lib9C나 Libplanet 에서 필수로 받고 있어서 좀 애매한 부분이 있습니다.
Command 안에서 default 를 만들어서 넘겨주거나... > 이거 이러면 안될 것 같은데
