### ISSUE TITLE
Design new config structure

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.Headless#1468]
Continue from #1461

Plan: https://planetarium.notion.site/Rebuild-genesis-012393c7f47c4b8fb16fd5fcef8febdc (written in Korean)

**Comment by U-lis** [comment]
Current implementation: [Notion](https://www.notion.so/planetarium/Rebuild-genesis-012393c7f47c4b8fb16fd5fcef8febdc)

**Comment by U-lis** [comment]
[New genesis config structure](https://www.notion.so/planetarium/Rebuild-genesis-012393c7f47c4b8fb16fd5fcef8febdc#c585609d273f439b97dbe97154d90a52)
