### ISSUE TITLE
Failing `Mine` Test in `GenesisCommandTest` 

### ISSUE THREAD

**Issue by area363** [planetarium/NineChronicles.Headless#1487]
It appears that the CI test for `Mine` in `GenesisCommandTest`  is failing after https://github.com/planetarium/NineChronicles.Headless/pull/1470.

Is there any plan to fix this issue? 🙏 @U-lis cc @moreal

**Comment by U-lis** [comment]
I've worked this one, so I'll check this issue.
@area363 @moreal Where can I check the failing test? I think `github actions` is not the one.
After finding what's the reason, Let you know how to fix ASAP.

**Comment by area363** [comment]
https://github.com/planetarium/NineChronicles.Headless/runs/7851059698?check_suite_focus=true#step:5:6839
I think you can refer to this log to see which tests are failing!

**Comment by U-lis** [comment]
@area363  I got what's the issue. Working on #1470 , I rebuild config structure of genesis command and did not applied it to test.
Sorry for breaking integrity and I'm gonna fix it right away.

quick question: Where should my bugfix PR goes to? `deveplopment` or `rc-v100270-development`?

**Comment by area363** [comment]
Awesome, you can direct it straight to `development` 👍
