### ISSUE TITLE
Wrong deprecation message

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.Headless#1540]
<img width="477" alt="image" src="https://user-images.githubusercontent.com/128436/188354150-f6ad1cfa-0fa6-4482-8680-cff5bff6390c.png">

But there is no `transactionQuery.stageTx`. I think that it meant `mutation { stageTransactions() }`.

**Comment by moreal** [comment]
It seems resolved already 👀 

https://github.com/planetarium/NineChronicles.Headless/blob/11bcdc01fa914093642a76c0adea10cb779b7529/NineChronicles.Headless/GraphTypes/StandaloneMutation.cs#L96
