### ISSUE TITLE
Publish `NineChornicles.Headless` with shortcut naming, `ncd`

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles.Headless#1687]
### Discussed in https://github.com/planetarium/NineChronicles.Headless/discussions/1641

<div type='discussions-op-text'>

<sup>Originally posted by **moreal** October 19, 2022</sup>
In case of go-ethereum's, the node implementation's filename is `geth`. And users can use it by running `geth`. But in Nine Chronicles, users should run `NineChronicles.Headless.Executable[.exe]` to run 9c node. I'd like to discuss the shortcut naming of the file.</div>

**Comment by boscohyun** [comment]
The `nc` in `ncd` seems to be `NineChronicles`, but if so, what does the `d` stand for?

**Comment by moreal** [comment]
> The `nc` in `ncd` seems to be `NineChronicles`, if so, what does the `d` stand for?

From the discussion, it is stand for daemon.
