### ISSUE TITLE
Require Some actions Implemented to actionTxQuery

### ISSUE THREAD

**Issue by Akamig** [planetarium/NineChronicles.Headless#1748]
Currently 9c-launcher is substituting raw action data generation from Headless CLI to GraphQL actionTxQuery,
But unfortunately some of actions required by launcher was not implemented in actionTxQuery, so I hope we can have them.

following actions are required to implemented.
- [x] `activateAccount`
- [x] ~`monsterCollect`~
- [x] ~`claimMonsterCollectionReward`~

**Comment by U-lis** [comment]
Doesn't `claimMonsterCollectionReward` action deprecated? As I know, `ClaimStakeReward` is the right action to claim NCG staking reward current days and `claimMonsterCollectionReward` is for old NCG staking v1.
Could you check about this action?

**Comment by Akamig** [comment]
From what I look, It seems `claimMonsterCollectionReward` action is still in use for people didn't migrated from v1 staking / v1 launcher yet. I'm planning to end support on V1 launcher in the near future, but until then I think this action is needed.

**Comment by Akamig** [comment]
....aaaaaaaand I just checked 9cscan and seems no single claimMonsterCollectionReward was happened last 5 months. I think we don't have to implement it.

**Comment by U-lis** [comment]
I'll take this and push my workaround to upstream branch.
Please test and modify it and merge within your launcher development schedule.

**Comment by U-lis** [comment]
@Akamig Also in case of `monsterCollect`, I searched `monster_collect` and `monster_collect2` action type on 9cscan and latest action is an year ago. It's maybe NCG staking v1 action I think and this also not need to be implemented. Can you double check this action?

**Comment by Akamig** [comment]
@U-lis double checked. So, now we can focus only on activate_account query.

**Comment by U-lis** [comment]
Please use [this branch](https://github.com/planetarium/ninechronicles.headless/tree/feature/missing-action-tx-query) to test action and GQL and please merge that branch on your own.

**Comment by Akamig** [comment]
https://github.com/planetarium/NineChronicles.Headless/pull/1722
