### ISSUE TITLE
add headless tx-comm-disable mode

### ISSUE THREAD

**Issue by longfin** [planetarium/NineChronicles.Headless#1830]

**Comment by longfin** [comment]
@area363 we may leverage  this policy https://github.com/planetarium/lib9c/blob/99cd2e26e6e6ff38bd1d8d5177886906ef197b96/Lib9c/StagePolicy.cs

**Comment by area363** [comment]
1. Add option to adjust tx-pool size

**Comment by area363** [comment]
tx-comm disabling did not help with memory usage increasing uncontrollably 😢.

But I've found that https://github.com/planetarium/libplanet/blob/main/Libplanet.Net/BlockCompletion.cs#L30 changing the default value of `window` to 0 limits the headless memory usage to 10GB so I'm closing this issue and continuing my investigation in `BlockCompletion`.
