### ISSUE TITLE
Remove unused ArenaParticipantsWorker related code

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles.Headless#2579]
## Background

[ArenaParticipantsWorker.cs](https://github.com/planetarium/NineChronicles.Headless/blob/v200220/NineChronicles.Headless/ArenaParticipantsWorker.cs) is no longer used. should remove the unused related code.

## Work Items

 - Remove [`ArenaParticipantsWorker.cs`](https://github.com/planetarium/NineChronicles.Headless/blob/2b3dfb4ec0d4ab2b4309213b12ac3713c9b151e5/NineChronicles.Headless/ArenaParticipantsWorker.cs) file.
 - Remove [`ArenaParticipantsWorkerTest.cs`](https://github.com/planetarium/NineChronicles.Headless/blob/2b3dfb4ec0d4ab2b4309213b12ac3713c9b151e5/NineChronicles.Headless.Tests/ArenaParticipantsWorkerTest.cs) file

**Comment by upa-r-upa** [comment]
Hello. I'd like to help with this issue!

**Comment by moreal** [comment]
> Hello. I'd like to help with this issue!

@upa-r-upa Of course!! I assigned you!
