### ISSUE TITLE
Support more minterless CurrencyEnumType

### ISSUE THREAD

**Issue by ipdae** [planetarium/NineChronicles.Headless#2581]
## Context

Support more `CurrencyEnumType` members, corresponding to minterless [currencies](https://github.com/planetarium/lib9c/blob/v200220/Lib9c/Currencies.cs#L26-L66)

## Tips

You should introduce a new enum member of [`CurrencyEnumType.CurrencyEnum`](https://github.com/planetarium/NineChronicles.Headless/blob/accf033a143ea2f11a584a2218a64a1d3c7d16b6/NineChronicles.Headless/GraphTypes/CurrencyEnumType.cs#L6-L13)

https://github.com/planetarium/NineChronicles.Headless/blob/accf033a143ea2f11a584a2218a64a1d3c7d16b6/NineChronicles.Headless/GraphTypes/CurrencyEnumType.cs#L6-L13

**Comment by river20s** [comment]
제가 해보겠습니다.
