### ISSUE TITLE
Use AvatarState.Create static method in fixtures

### ISSUE THREAD

**Issue by U-lis** [planetarium/NineChronicles.Headless#2584]
You can use just `AvatarState.Create` static method, same method signature with the previous `AvatarState` constructor. (Because there are already sheets)

_Originally posted by @moreal in https://github.com/planetarium/NineChronicles.Headless/pull/2583#pullrequestreview-2302066820_

**Comment by moreal** [comment]
It is resolved by https://github.com/planetarium/NineChronicles.Headless/commit/263a2b7dbdb41176376554bc431206b681643f42#diff-23735375e550783dccce4bfd3670cfdf42b2cdd6edeaf5f398e1393fd863ff12 and it will be applied to `main` and `development` branch at September 31
