### ISSUE TITLE
Deprecate `--arenaParticipantsSync` option

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles.Headless#2598]
## Context

Since #2596, `--arenaParticipantsSync` CLI option becomes not to be used. So it should be deprecated.

## Work items

Please notice users to know that "the option is deprecated so you shouldn't use the option anymore", through stderr output.

## Tips

Since `arenaParticipantsSync` default value is `true`, you should check the case where `arenaParticipantsSync` is `false`.

**Comment by Gongkirby** [comment]
제가 하겠습니다!
