### ISSUE TITLE
Enable nullable feature over projects

### ISSUE THREAD

**Issue by moreal** [planetarium/NineChronicles.Headless#349]
Since C# 8.0, *Nullable references* has been introduced and made able to control `null` more efficiently. So I suggest to enable the feature over all projects in this repository, by adding this line into each *.csproj* files.

```XML
<Nullable>enable</Nullable>
```

You can see more https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references.

**Comment by dahlia** [comment]
The later we enable nullable references, the harder we adopt it.

**Comment by moreal** [comment]
> 
> 
> The later we enable nullable references, the harder we adopt it.

As you said, the later, the more difficult it will be to apply, so I will take it to the 9C Backend project task and try to apply it ASAP.
