### ISSUE TITLE
New GQL Query Request - Item Grade (+0/+1/+2) and respective stats.

### ISSUE THREAD

**Issue by FioX0** [planetarium/NineChronicles.Headless#507]
Hi Team,

Myself and SoFloppy are both working on a system to our own projects that involves displaying Character Equipment back to the end-user.

There are a couple of things that are currently not present and would be really nice to have.

- There's no way to identify if an item is base/+1/+2/+3 or so on.
- Item's values are always base value, even if they are upgraded.

![image](https://user-images.githubusercontent.com/81689614/120891470-bd1c9a00-c600-11eb-91b3-6527d2339e26.png)

This query is out-of-date as it was before v45 and the structure has slightly changed and currently avatar queries do not work as per issue #506. But for reference it's below;

```graphql
query {
  stateQuery{
    avatar(address: "63b6fef274118719790f63865e63a2cd26ff14dc")
		{inventory{
      equipments
			{id,itemId,equipped,elementalType,grade,itemSubType,itemType}
    }
    }
  }
}
```

**Comment by ipdae** [comment]
support on #535 . target release version is v100055
