### ISSUE TITLE
GraphQL query for `isWorldUnlocked` returns a wrong value

### ISSUE THREAD

**Issue by greymistcube** [planetarium/NineChronicles.Headless#518]
The following query

```
query
{
    stateQuery
    {
        agent(address: "<address>")
        {
            avatarStates
            {
                worldInformation
                {
                    isStageCleared(stageId: <stage_id>)
                    isWorldUnlocked(worldId: <world_id>)
                }
            }
        }
    }
}
```

does not seem to work as intended. For example, if a game character has cleared stage `190` and not yet cleared `191`, expected query result for

```
isStagedCleared(stageId: 190)
isWorldUnlocked(worldId: 5)
```

should be

```
"isStagedCleared": true,
"isWorldUnlocked": false
```

but instead returns

```
"isStagedCleared": true,
"isWorldUnlocked": true
```

Upon further inspection, it seems the query result for `isStagedCleared` and `isWorldUnlocked` are always the same. I suspect `isWorldUnlocked` is wrongly querying `isStagedCleared` instead.

**Comment by ipdae** [comment]
fixed in #561
