### ISSUE TITLE
Too many log files in directory

### ISSUE THREAD

**Issue by Namyujeong** [planetarium/NineChronicles.Headless#527]
these files are safe to delete right?
It keeps piling up and eat few GB of space. And doesn't seem to be cleared after clearing cache etc too

![image](https://user-images.githubusercontent.com/41294407/122561061-537aa200-d07c-11eb-88c2-f38214a061c4.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1141562434100787/1200502990605130) by [Unito](https://www.unito.io)

**Comment by longfin** [comment]
It seems that we changed the key for AWS authentication, and the S3 upload did not work. [Serilog.AmazonS3 sink doesn't delete local log files if there is an error](https://github.com/SeppPenner/Serilog.Sinks.AmazonS3/blob/95bd0ec9e29217ce8b8aefc5d69dd797e9644840/src/Serilog.Sinks.AmazonS3/Sinks/AmazonS3/AmazonS3Sink.cs#L87-L97)

I'll handle this issue by purging old logs when start-up. (as #523)
