### ISSUE TITLE
AvatarStates Inventory GQL Broken with v55+

### ISSUE THREAD

**Issue by FioX0** [planetarium/NineChronicles.Headless#565]
As of v55, the inventory GQL returns a resolve field error.

When I tested this around, it seems to break if the avatar being queried has an item on the marketboard. Seems to be related to the changes done in v55 where items on the marketboard are visible in the inventory but in a greyed out state.

`query {
  stateQuery{
    agent(address: "0xa49d64c31A2594e8Fb452238C9a03beFD1119963")
{avatarStates{agentAddress,actionPoint,level,name,address,updatedAt,inventory{equipments{equipped,itemId,grade,elementalType}}}}
  }
}`

`{
  "errors": [
    {
      "message": "Error trying to resolve field 'inventory'.",
      "locations": [
        {
          "line": 11,
          "column": 9
        }
      ],
      "path": [
        "stateQuery",
        "agent",
        "avatarStates",
        0,
        "inventory"
      ],
      "extensions": {
        "code": "INVALID_OPERATION",
        "codes": [
          "INVALID_OPERATION"
        ]
      }
    },
    {
      "message": "Error trying to resolve field 'inventory'.",
      "locations": [
        {
          "line": 11,
          "column": 9
        }
      ],
      "path": [
        "stateQuery",
        "agent",
        "avatarStates",
        1,
        "inventory"
      ],
      "extensions": {
        "code": "INVALID_OPERATION",
        "codes": [
          "INVALID_OPERATION"
        ]
      }
    },
    {
      "message": "Error trying to resolve field 'inventory'.",
      "locations": [
        {
          "line": 11,
          "column": 9
        }
      ],
      "path": [
        "stateQuery",
        "agent",
        "avatarStates",
        2,
        "inventory"
      ],
      "extensions": {
        "code": "INVALID_OPERATION",
        "codes": [
          "INVALID_OPERATION"
        ]
      }
    }
  ],
  "data": {
    "stateQuery": {
      "agent": {
        "avatarStates": null
      }
    }
  },
  "extensions": {}
}`

**Comment by ipdae** [comment]
Thanks for reporting. #557 fix this issue.
