### ISSUE TITLE
Re: #722 - GQL HnS once more broken

### ISSUE THREAD

**Issue by FioX0** [planetarium/NineChronicles.Headless#805]
Hi team, 

sadly once more HnS got made a change against it and the gql equivalent isnt updated. when sending the gql query it accepts it but then flags an error 99.

As it is a reoccurring trend, may i suggest to ad some unit test around this, so you can easily identify if something broke.

thanks

**Comment by area363** [comment]
Could you add a specific query that caused the query to fail? It works when I tried it so I'm wondering which arguments were used when it caused the error. Thanks!

**Comment by kaila52** [comment]
How long will this issue be resolved?
