### ISSUE TITLE
GQL Query Request - combinationSlotAddresses details (Index and Duration)

### ISSUE THREAD

**Issue by FioX0** [planetarium/NineChronicles.Headless#872]
Hi Team,

I have noticed that we have a GQL Query to get the addresses of each "Upgrading/Crafting" slot.

`query {
  stateQuery {
    agent(address: "0x083B1ad95AF96B754E055384B260a3024d02c7ba") {
      avatarStates {
        name
        level
        address
        combinationSlotAddresses
      }
    }
  }
}`

Any plans to allow us to query remaining time on these combinationSlotAddresses?
As the timers were pretty static in the past it was quite simple to give it a the static value depending on the item's tier. As it is now pretty much dynamic and even depending on what the sword has stats wise, it would be amazing if you could get something along the lines of what you have done with dailyRewardReceivedIndex, where we know the index and then another integer with the duration for this specific craft. 

Example:
CombinationSlotAddresses
int combinationStartIndex
int combinationDuration

That way it would be super simple to just to StartIndex + duration = Block where craft finishes.

**Comment by ipdae** [comment]
I've checked [CombinationSlotStateType](https://github.com/planetarium/NineChronicles.Headless/blob/development/NineChronicles.Headless/GraphTypes/States/CombinationSlotStateType.cs) is ready but not used anywhere. but there are more information We want to support the avatar state query with the following fields like this.

```
query {
  stateQuery {
    avatar(avatarAddress: "") {
      combinationSlots {
        address
        startBlockIndex
        unlockBlockIndex
        requiredBlockIndex
      }
    }
  }
}
```

- startBlockIndex is craft started blockIndex.
- unlockBlockIndex is craft finished blockIndex.
- requredBlockIndex is craft duration.
